version: '3'

services:

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
    ports:
      - '6541:5432'

  app:
    build: /
    container_name: tasklist
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

