spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist-ss
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

security:
  jwt:
    secret: cnczclEzUnEzclEzUnFyUVJHU0RHWkdaR0ZHRkdGREdnZGdzZ2FlZ2FlZ2FlZ2ZkZ2FnZWRmZ2RqeXVreXVreXVreXVr
    access: 6000000
    refresh: 1296000000