spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist-ss
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true