spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=public
    username: ${DB_USER}
    password: ${DB_PASS}

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASS}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret: ${SECRET}
    access: ${ACCESS}
    refresh: ${REFRESH}

springdoc:
  override-with-generic-response: false