drop table if exists users, user_roles;

create table if not exists users (
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    username varchar(255) not null unique,
    email    varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists user_roles (
    user_id bigint      not null references users (id) on delete cascade,
    role    varchar(64) not null,
    primary key (user_id, role)
);