create table if not exists users
(
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    username varchar(255) not null unique,
    email    varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists user_roles
(
    user_id bigint      not null references users (id) on delete cascade,
    role    varchar(64) not null,
    primary key (user_id, role)
);

create table if not exists tasks
(
    id               bigint generated by default as identity primary key,
    title            varchar(128) not null,
    description      varchar(512) not null,
    priority         varchar(16)  not null,
    status           varchar(16)  not null,
    created_at       TIMESTAMP    not null,
    expires_at       TIMESTAMP    not null,
    last_modified_at TIMESTAMP,
    notify           boolean,
    user_id          bigint references users (id) on delete cascade
);